# Generated by Django 5.0.1 on 2024-01-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Contact Person')),
                ('email', models.CharField(max_length=50, verbose_name='Contact Email')),
                ('contact', models.IntegerField(verbose_name='Contact Number')),
                ('message', models.CharField(max_length=200, verbose_name='Suggestions')),
            ],
        ),
    ]
