# Generated by Django 5.0.1 on 2024-02-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=40, verbose_name='Topic Name')),
                ('date_of_creation', models.DateField(verbose_name='Date of Creation')),
                ('blog_script', models.TextField(verbose_name='Blog Script')),
            ],
        ),
    ]
