# Generated by Django 5.0.1 on 2024-02-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogWebApp', '0004_fileattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileattachment',
            options={'verbose_name_plural': 'File Attachments'},
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('doc', 'Document'), ('excel', 'Excel')], default='image', max_length=10, verbose_name='File Type'),
        ),
    ]
