# Generated by Django 5.0.1 on 2024-02-25 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogWebApp', '0009_contactinfo_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.AddField(
            model_name='blogentry',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated At'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='date_of_creation',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Creation'),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='categories',
            field=models.ManyToManyField(related_name='blog_entries', to='blogWebApp.blogcategory', verbose_name='Categories'),
        ),
    ]
