# Generated by Django 5.0.1 on 2024-02-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogWebApp', '0010_blogcategory_blogentry_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='message',
            field=models.TextField(max_length=200, verbose_name='Suggestions'),
        ),
    ]
