# Generated by Django 5.0.1 on 2024-02-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogWebApp', '0011_alter_contactinfo_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='contact',
            field=models.CharField(max_length=15, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Contact Email'),
        ),
    ]
