# Generated by Django 5.0.1 on 2024-02-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogWebApp', '0012_alter_contactinfo_contact_alter_contactinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(choices=[('technology', 'Technology'), ('lifestyle', 'Lifestyle'), ('food', 'Food'), ('fitness', 'Fitness'), ('travel', 'Travel'), ('fashion', 'Fashion'), ('finance', 'Finance'), ('entertainment', 'Entertainment'), ('education', 'Education'), ('parenting', 'Parenting')], max_length=100, verbose_name='Category Name'),
        ),
    ]
