# Generated by Django 5.0.1 on 2024-03-26 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogWebApp', '0013_alter_blogcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2024, 3, 26, 19, 53, 21, 384575, tzinfo=datetime.timezone.utc), verbose_name='Date of Creation'),
        ),
    ]
