# Generated by Django 5.0.1 on 2024-03-26 19:58

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogWebApp', '0015_alter_blogentry_date_of_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2024, 3, 26, 19, 58, 1, 879670, tzinfo=datetime.timezone.utc), verbose_name='Date of Creation'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
    ]
